### ISSUE TITLE
２回目以降の実行が１回目の結果を返す

### ISSUE THREAD

**Issue by mptits** [lll-lll-lll-lll/sent-pattern#2]
1) The man is my friend.
2) The man was my friend.
などのように、似た文章で実行すると、１回目の解析結果が返されてしまいます。

3) He is 〜
のように似ていない文章で実行すると、正常に結果が返されます。

その後再度(2)の文章で実行しても(1)の結果が返されます。

修正していただけると嬉しいです。

**Comment by lll-lll-lll-lll** [comment]
@mptits 

もしよければサンプルのコードとか見せてもらうことって可能ですか?

**Comment by mptits** [comment]
コードはサンプルのままです。

#
import spacy
from sent_pattern import tags
nlp = spacy.load("en_core_web_lg")
doc = nlp("he gives me something")
dep_list = tags.create_dep_list(doc)
elements  = tags.create_elements(dep_list=dep_list)
p  = tags.create_sent_pattern(elements=elements)
pattern = p.pattern_type
#


pattern.subject.root.text
pattern.verb.root
pattern.abbreviation

等は毎回結果が格納されるのですが、
spans_str とか dict  (非公開？) が更新されず、文型ごとに古い値が格納されたままです。

※ pattern.abbreviationのみ出力することを意図したモジュールかもしれませんが、学習者としては
S : xxxxx , V : xxxxxx , C : xxxxxxx と出力されたものを見たいので、できればこれらの変数も毎回更新されるようにしていただけると嬉しいです。

**Comment by lll-lll-lll-lll** [comment]
もしかしたら`spans_str`変数ではなく、`span_dict_str`を参照してるかもしれないですね。
非公開にしてなかったので、前の結果が返って来てるのかもしれません。
次のバージョンでその変数を非公開に変更したいと思います。
v0.1.0以上だと以下のサンプルだと`text`変数を変えても問題なく動くと思います

```py
import spacy
from sent_pattern import tags
text_1 = "The man is my friend."
text_2 = "The man was my friend."
nlp = spacy.load("en_core_web_sm")
doc = nlp(text_1)
dep_list = tags.create_dep_list(doc)
elements  = tags.create_elements(dep_list=dep_list)
p  = tags.create_sent_pattern(elements=elements)
pattern = p.pattern_type
print(pattern.abbreviation)
print(pattern.spans_str)

# output
SVC
{'S': 'The man', 'V': 'is', 'C': 'my friend'}

SVC
{'S': 'The man', 'V': 'was', 'C': 'my friend'}
```

**Comment by mptits** [comment]
動作確認できました、ありがとうございます！
